export const MESSAGE_TYPES = {
  // Akashi
  AKASHI_STATUS_UPDATE: 'AKASHI_STATUS_UPDATE',
  REQUEST_AKASHI_STATUS: 'REQUEST_AKASHI_STATUS',

  // Calendar
  REQUEST_UPCOMING_EVENTS: 'REQUEST_UPCOMING_EVENTS',
  REFRESH_CALENDAR: 'REFRESH_CALENDAR',

  // Settings
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  // Auth
  LOGIN: 'LOGIN',

  // Meeting skip
  SKIP_MEETING: 'SKIP_MEETING',
  UNSKIP_MEETING: 'UNSKIP_MEETING',

  // Combined status (for popup)
  GET_STATUS: 'GET_STATUS',
};
